/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsChatMessageIndexRouteImport } from './routes/components/chat-message/index'
import { Route as ComponentsChatInputIndexRouteImport } from './routes/components/chat-input/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsChatMessageIndexRoute =
  ComponentsChatMessageIndexRouteImport.update({
    id: '/components/chat-message/',
    path: '/components/chat-message/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComponentsChatInputIndexRoute =
  ComponentsChatInputIndexRouteImport.update({
    id: '/components/chat-input/',
    path: '/components/chat-input/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/components/chat-input': typeof ComponentsChatInputIndexRoute
  '/components/chat-message': typeof ComponentsChatMessageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/components/chat-input': typeof ComponentsChatInputIndexRoute
  '/components/chat-message': typeof ComponentsChatMessageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/components/chat-input/': typeof ComponentsChatInputIndexRoute
  '/components/chat-message/': typeof ComponentsChatMessageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/components/chat-input' | '/components/chat-message'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/components/chat-input' | '/components/chat-message'
  id: '__root__' | '/' | '/components/chat-input/' | '/components/chat-message/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComponentsChatInputIndexRoute: typeof ComponentsChatInputIndexRoute
  ComponentsChatMessageIndexRoute: typeof ComponentsChatMessageIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/chat-message/': {
      id: '/components/chat-message/'
      path: '/components/chat-message'
      fullPath: '/components/chat-message'
      preLoaderRoute: typeof ComponentsChatMessageIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/chat-input/': {
      id: '/components/chat-input/'
      path: '/components/chat-input'
      fullPath: '/components/chat-input'
      preLoaderRoute: typeof ComponentsChatInputIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComponentsChatInputIndexRoute: ComponentsChatInputIndexRoute,
  ComponentsChatMessageIndexRoute: ComponentsChatMessageIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
